<?php
/**
 * game_data_spells.php
 * Актуальные параметры заклинаний (Home Village).
 *
 * Этот файл возвращает массив, который ПЕРЕОПРЕДЕЛЯЕТ соответствующие ключи
 * из game_data_entities.php через array_replace() в system/game_data.php.
 *
 * Источник численных параметров: Clash of Clans Wiki (Fandom) страницы заклинаний.
 */

if (!defined('TYPE_SPELL')) define('TYPE_SPELL', 'spell');
if (!defined('TYPE_DARK_SPELL')) define('TYPE_DARK_SPELL', 'dark_spell');

return [

  // === Elixir spells ===
  'lightning_spell' => [
    'name' => 'Молния',
    'type' => TYPE_SPELL,
    'desc' => 'Наносит урон выбранной цели молнией. Отлично подходит для добивания ключевой обороны.',
    'effect' => 'Наносит высокий разовый урон по области.',
    'targets' => 'any',
    'usage' => 'Снос ПВО/ключевой обороны, добивание героев.',
    'unlock_th' => 5,
    // Время варки (как в оригинальном CoC): 3 минуты на 1 место
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 15000,
    'brew_res_type' => 'elixir',
    'housing_space' => 1,
    'radius' => 2.0,
    'stun_time' => 0.1,
    'levels' => [
      1  => ['damage' => 150, 'cost' => 0,        'res_type' => 'elixir', 'time' => 0,       'lab_req' => 0,  'th_req' => 0],
      2  => ['damage' => 180, 'cost' => 50000,    'res_type' => 'elixir', 'time' => 7200,    'lab_req' => 1,  'th_req' => 0],
      3  => ['damage' => 210, 'cost' => 100000,   'res_type' => 'elixir', 'time' => 14400,   'lab_req' => 2,  'th_req' => 0],
      4  => ['damage' => 240, 'cost' => 200000,   'res_type' => 'elixir', 'time' => 21600,   'lab_req' => 3,  'th_req' => 0],
      5  => ['damage' => 270, 'cost' => 600000,   'res_type' => 'elixir', 'time' => 86400,   'lab_req' => 6,  'th_req' => 0],
      6  => ['damage' => 320, 'cost' => 1500000,  'res_type' => 'elixir', 'time' => 129600,  'lab_req' => 7,  'th_req' => 0],
      7  => ['damage' => 400, 'cost' => 2500000,  'res_type' => 'elixir', 'time' => 259200,  'lab_req' => 8,  'th_req' => 0],
      8  => ['damage' => 480, 'cost' => 4200000,  'res_type' => 'elixir', 'time' => 302400,  'lab_req' => 9,  'th_req' => 0],
      9  => ['damage' => 560, 'cost' => 6300000,  'res_type' => 'elixir', 'time' => 432000,  'lab_req' => 10, 'th_req' => 0],
      10 => ['damage' => 600, 'cost' => 10000000, 'res_type' => 'elixir', 'time' => 518400,  'lab_req' => 13, 'th_req' => 0],
      11 => ['damage' => 640, 'cost' => 13500000, 'res_type' => 'elixir', 'time' => 604800,  'lab_req' => 14, 'th_req' => 0],
      12 => ['damage' => 680, 'cost' => 18500000, 'res_type' => 'elixir', 'time' => 864000,  'lab_req' => 15, 'th_req' => 0],
      13 => ['damage' => 720, 'cost' => 27000000, 'res_type' => 'elixir', 'time' => 1209600, 'lab_req' => 16, 'th_req' => 0],
    ],
  ],

  'healing_spell' => [
    'name' => 'Лечение',
    'type' => TYPE_SPELL,
    'desc' => 'Восстанавливает здоровье войскам в области действия волнами исцеления.',
    'effect' => 'Лечит союзные войска в области действия.',
    'targets' => 'ground',
    'usage' => 'Поддержка наземных пушей (хоги/минёры и т.п.).',
    'unlock_th' => 6,
    'brew_time' => 360,
    'training_time' => 0,
    'brew_cost' => 15000,
    'brew_res_type' => 'elixir',
    'housing_space' => 2,
    'radius' => 5.0,
    'pulses' => 41,
    'time_between_pulses' => 0.3,
    'duration' => 12.3,
    'levels' => [
      1  => ['total_healing' => 615,  'healing_per_pulse' => 15, 'hero_total_healing' => 338.25,  'cost' => 0,        'res_type' => 'elixir', 'time' => 0,       'lab_req' => 0,  'th_req' => 0],
      2  => ['total_healing' => 820,  'healing_per_pulse' => 20, 'hero_total_healing' => 451,     'cost' => 75000,    'res_type' => 'elixir', 'time' => 10800,   'lab_req' => 2,  'th_req' => 0],
      3  => ['total_healing' => 1025, 'healing_per_pulse' => 25, 'hero_total_healing' => 563.75,  'cost' => 150000,   'res_type' => 'elixir', 'time' => 21600,   'lab_req' => 4,  'th_req' => 0],
      4  => ['total_healing' => 1230, 'healing_per_pulse' => 30, 'hero_total_healing' => 676.5,   'cost' => 300000,   'res_type' => 'elixir', 'time' => 43200,   'lab_req' => 5,  'th_req' => 0],
      5  => ['total_healing' => 1435, 'healing_per_pulse' => 35, 'hero_total_healing' => 789.25,  'cost' => 900000,   'res_type' => 'elixir', 'time' => 86400,   'lab_req' => 6,  'th_req' => 0],
      6  => ['total_healing' => 1640, 'healing_per_pulse' => 40, 'hero_total_healing' => 902,     'cost' => 1800000,  'res_type' => 'elixir', 'time' => 129600,  'lab_req' => 7,  'th_req' => 0],
      7  => ['total_healing' => 1845, 'healing_per_pulse' => 45, 'hero_total_healing' => 1014.75, 'cost' => 3000000,  'res_type' => 'elixir', 'time' => 259200,  'lab_req' => 8,  'th_req' => 0],
      8  => ['total_healing' => 2050, 'healing_per_pulse' => 50, 'hero_total_healing' => 1127.5,  'cost' => 6000000,  'res_type' => 'elixir', 'time' => 432000,  'lab_req' => 11, 'th_req' => 0],
      9  => ['total_healing' => 2255, 'healing_per_pulse' => 55, 'hero_total_healing' => 1240.25, 'cost' => 11000000, 'res_type' => 'elixir', 'time' => 561600,  'lab_req' => 13, 'th_req' => 0],
      10 => ['total_healing' => 2460, 'healing_per_pulse' => 60, 'hero_total_healing' => 1353,    'cost' => 14000000, 'res_type' => 'elixir', 'time' => 604800,  'lab_req' => 14, 'th_req' => 0],
      11 => ['total_healing' => 2747, 'healing_per_pulse' => 67, 'hero_total_healing' => 1510.85, 'cost' => 19000000, 'res_type' => 'elixir', 'time' => 907200,  'lab_req' => 15, 'th_req' => 0],
      12 => ['total_healing' => 3075, 'healing_per_pulse' => 75, 'hero_total_healing' => 1691.25, 'cost' => 29000000, 'res_type' => 'elixir', 'time' => 1296000, 'lab_req' => 16, 'th_req' => 0],
    ],
  ],

  'rage_spell' => [
    'name' => 'Ярость',
    'type' => TYPE_SPELL,
    'desc' => 'Усиливает урон и скорость передвижения союзных войск в области действия.',
    'effect' => 'Увеличивает урон и скорость союзных войск.',
    'targets' => 'any',
    'usage' => 'Ускорение пробива, максимальный DPS (шары/драконы/кор).',
    'unlock_th' => 7,
    'brew_time' => 360,
    'training_time' => 0,
    'brew_cost' => 23000,
    'brew_res_type' => 'elixir',
    'housing_space' => 2,
    'radius' => 5.0,
    'duration' => 18,
    'levels' => [
      1 => ['damage_increase_pct' => 130, 'speed_increase' => 20, 'cost' => 0,       'res_type' => 'elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['damage_increase_pct' => 140, 'speed_increase' => 22, 'cost' => 400000,  'res_type' => 'elixir', 'time' => 21600,  'lab_req' => 3,  'th_req' => 0],
      3 => ['damage_increase_pct' => 150, 'speed_increase' => 24, 'cost' => 800000,  'res_type' => 'elixir', 'time' => 43200,  'lab_req' => 4,  'th_req' => 0],
      4 => ['damage_increase_pct' => 160, 'speed_increase' => 26, 'cost' => 1000000, 'res_type' => 'elixir', 'time' => 86400,  'lab_req' => 5,  'th_req' => 0],
      5 => ['damage_increase_pct' => 170, 'speed_increase' => 28, 'cost' => 2000000, 'res_type' => 'elixir', 'time' => 172800, 'lab_req' => 6,  'th_req' => 0],
      6 => ['damage_increase_pct' => 180, 'speed_increase' => 30, 'cost' => 5000000, 'res_type' => 'elixir', 'time' => 345600, 'lab_req' => 10, 'th_req' => 0],
    ],
  ],

  'jump_spell' => [
    'name' => 'Прыжок',
    'type' => TYPE_SPELL,
    'desc' => 'Позволяет войскам перепрыгивать через стены в зоне действия.',
    'effect' => 'Позволяет наземным войскам игнорировать стены в области.',
    'targets' => 'ground',
    'usage' => 'Проход в центр базы, обход “кольцевых” стен.',
    'unlock_th' => 9,
    'brew_time' => 360,
    'training_time' => 0,
    'brew_cost' => 23000,
    'brew_res_type' => 'elixir',
    'housing_space' => 2,
    'radius' => 3.5,
    'boost_time' => 1,
    'levels' => [
      1 => ['duration' => 20,  'cost' => 0,       'res_type' => 'elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['duration' => 40,  'cost' => 1000000, 'res_type' => 'elixir', 'time' => 86400,  'lab_req' => 5,  'th_req' => 0],
      3 => ['duration' => 60,  'cost' => 2000000, 'res_type' => 'elixir', 'time' => 172800, 'lab_req' => 8,  'th_req' => 0],
      4 => ['duration' => 80,  'cost' => 5000000, 'res_type' => 'elixir', 'time' => 345600, 'lab_req' => 11, 'th_req' => 0],
      5 => ['duration' => 100, 'cost' => 8000000, 'res_type' => 'elixir', 'time' => 561600, 'lab_req' => 13, 'th_req' => 0],
    ],
  ],

  'freeze_spell' => [
    'name' => 'Заморозка',
    'type' => TYPE_SPELL,
    'desc' => 'Останавливает оборону и вражеские войска в области действия.',
    'effect' => 'Замораживает здания/войска, отключая их.',
    'targets' => 'any',
    'usage' => 'Контроль Инферно/Орла/ПВО, защита героев.',
    'unlock_th' => 9,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 12000,
    'brew_res_type' => 'elixir',
    'housing_space' => 1,
    'radius' => 3.5,
    'levels' => [
      1 => ['freeze_time' => 2.5, 'cost' => 0,        'res_type' => 'elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['freeze_time' => 3.0, 'cost' => 1200000, 'res_type' => 'elixir', 'time' => 86400,  'lab_req' => 7,  'th_req' => 0],
      3 => ['freeze_time' => 3.5, 'cost' => 1700000, 'res_type' => 'elixir', 'time' => 129600, 'lab_req' => 8,  'th_req' => 0],
      4 => ['freeze_time' => 4.0, 'cost' => 3000000, 'res_type' => 'elixir', 'time' => 172800, 'lab_req' => 8,  'th_req' => 0],
      5 => ['freeze_time' => 4.5, 'cost' => 4200000, 'res_type' => 'elixir', 'time' => 216000, 'lab_req' => 8,  'th_req' => 0],
      6 => ['freeze_time' => 5.0, 'cost' => 6000000, 'res_type' => 'elixir', 'time' => 302400, 'lab_req' => 9,  'th_req' => 0],
      7 => ['freeze_time' => 5.5, 'cost' => 7000000, 'res_type' => 'elixir', 'time' => 432000, 'lab_req' => 10, 'th_req' => 0],
    ],
  ],

  'clone_spell' => [
    'name' => 'Клон',
    'type' => TYPE_SPELL,
    'desc' => 'Клонирует войска в зоне действия до лимита вместимости.',
    'effect' => 'Клонирует войска в области (в пределах лимита).',
    'targets' => 'any',
    'usage' => 'Усиление воздушных атак (шары/драконы) через клон.',
    'unlock_th' => 10,
    'brew_time' => 540,
    'training_time' => 0,
    'brew_cost' => 38000,
    'brew_res_type' => 'elixir',
    'housing_space' => 3,
    'radius' => 3.5,
    'spell_duration' => 18,
    'cloned_lifespan' => 30,
    'levels' => [
      1 => ['cloned_capacity' => 22, 'cost' => 0,        'res_type' => 'elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['cloned_capacity' => 24, 'cost' => 1500000,  'res_type' => 'elixir', 'time' => 86400,  'lab_req' => 8,  'th_req' => 0],
      3 => ['cloned_capacity' => 26, 'cost' => 2500000,  'res_type' => 'elixir', 'time' => 172800, 'lab_req' => 8,  'th_req' => 0],
      4 => ['cloned_capacity' => 28, 'cost' => 3000000,  'res_type' => 'elixir', 'time' => 194400, 'lab_req' => 9,  'th_req' => 0],
      5 => ['cloned_capacity' => 30, 'cost' => 4000000,  'res_type' => 'elixir', 'time' => 216000, 'lab_req' => 9,  'th_req' => 0],
      6 => ['cloned_capacity' => 34, 'cost' => 5000000,  'res_type' => 'elixir', 'time' => 345600, 'lab_req' => 11, 'th_req' => 0],
      7 => ['cloned_capacity' => 38, 'cost' => 8000000,  'res_type' => 'elixir', 'time' => 432000, 'lab_req' => 12, 'th_req' => 0],
      8 => ['cloned_capacity' => 42, 'cost' => 9000000,  'res_type' => 'elixir', 'time' => 604800, 'lab_req' => 13, 'th_req' => 0],
    ],
  ],

  'invisibility_spell' => [
    'name' => 'Невидимость',
    'type' => TYPE_SPELL,
    'desc' => 'Делает союзные войска и здания в области невидимыми для обороны на время.',
    'effect' => 'Делает войска невидимыми (оборона перестаёт их атаковать).',
    'targets' => 'any',
    'usage' => 'Защита героев/саппорт атак, точечные стратегии.',
    'unlock_th' => 11,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 25000,
    'brew_res_type' => 'elixir',
    'housing_space' => 1,
    'radius' => 4.0,
    'levels' => [
      1 => ['duration' => 3.5,  'cost' => 0,        'res_type' => 'elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['duration' => 3.75, 'cost' => 5000000,  'res_type' => 'elixir', 'time' => 259200, 'lab_req' => 9,  'th_req' => 0],
      3 => ['duration' => 4.0,  'cost' => 6000000,  'res_type' => 'elixir', 'time' => 345600, 'lab_req' => 10, 'th_req' => 0],
      4 => ['duration' => 4.25, 'cost' => 7000000,  'res_type' => 'elixir', 'time' => 432000, 'lab_req' => 11, 'th_req' => 0],
    ],
  ],

  'recall_spell' => [
    'name' => 'Возврат',
    'type' => TYPE_SPELL,
    'desc' => 'Телепортирует выбранные войска обратно, освобождая место для их повторного развертывания.',
    'effect' => 'Телепортирует выбранные войска назад (в пределах лимита).',
    'targets' => 'any',
    'usage' => 'Ре-позиционирование героев/ключевых войск.',
    'unlock_th' => 13,
    'brew_time' => 360,
    'training_time' => 0,
    'brew_cost' => 33000,
    'brew_res_type' => 'elixir',
    'housing_space' => 2,
    'radius' => 5.0,
    'levels' => [
      1 => ['recalled_capacity' => 83, 'cost' => 0,        'res_type' => 'elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['recalled_capacity' => 89, 'cost' => 7500000,  'res_type' => 'elixir', 'time' => 604800, 'lab_req' => 11, 'th_req' => 0],
      3 => ['recalled_capacity' => 95, 'cost' => 8000000,  'res_type' => 'elixir', 'time' => 734400, 'lab_req' => 12, 'th_req' => 0],
    ],
  ],

  // NOTE: заклинание "Возрождение" отсутствует в Home Village оригинального Clash of Clans,
  // поэтому намеренно не включаем его в актуальные данные.

  // === Dark spells ===
  'poison_spell' => [
    'name' => 'Яд',
    'type' => TYPE_DARK_SPELL,
    'desc' => 'Наносит возрастающий урон врагам в области и замедляет их.',
    'effect' => 'Наносит урон и замедляет войска/героев в области.',
    'targets' => 'any',
    'usage' => 'Снятие клан-замка/скелетов, контроль героев.',
    'unlock_th' => 8,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 95,
    'brew_res_type' => 'dark_elixir',
    'housing_space' => 1,
    'radius' => 4.0,
    'duration' => 16,
    'levels' => [
      1  => ['max_damage_per_second' => 90,  'speed_decrease_pct' => 26, 'attack_rate_decrease_pct' => 35, 'cost' => 0,      'res_type' => 'dark_elixir', 'time' => 0,       'lab_req' => 0,  'th_req' => 0],
      2  => ['max_damage_per_second' => 115, 'speed_decrease_pct' => 30, 'attack_rate_decrease_pct' => 40, 'cost' => 5000,   'res_type' => 'dark_elixir', 'time' => 21600,   'lab_req' => 6,  'th_req' => 0],
      3  => ['max_damage_per_second' => 145, 'speed_decrease_pct' => 34, 'attack_rate_decrease_pct' => 45, 'cost' => 10000,  'res_type' => 'dark_elixir', 'time' => 64800,   'lab_req' => 7,  'th_req' => 0],
      4  => ['max_damage_per_second' => 180, 'speed_decrease_pct' => 38, 'attack_rate_decrease_pct' => 50, 'cost' => 21500,  'res_type' => 'dark_elixir', 'time' => 172800,  'lab_req' => 8,  'th_req' => 0],
      5  => ['max_damage_per_second' => 220, 'speed_decrease_pct' => 40, 'attack_rate_decrease_pct' => 55, 'cost' => 35000,  'res_type' => 'dark_elixir', 'time' => 259200,  'lab_req' => 9,  'th_req' => 0],
      6  => ['max_damage_per_second' => 260, 'speed_decrease_pct' => 42, 'attack_rate_decrease_pct' => 60, 'cost' => 55000,  'res_type' => 'dark_elixir', 'time' => 345600,  'lab_req' => 10, 'th_req' => 0],
      7  => ['max_damage_per_second' => 280, 'speed_decrease_pct' => 44, 'attack_rate_decrease_pct' => 65, 'cost' => 77500,  'res_type' => 'dark_elixir', 'time' => 432000,  'lab_req' => 11, 'th_req' => 0],
      8  => ['max_damage_per_second' => 300, 'speed_decrease_pct' => 46, 'attack_rate_decrease_pct' => 68, 'cost' => 100000, 'res_type' => 'dark_elixir', 'time' => 561600,  'lab_req' => 12, 'th_req' => 0],
      9  => ['max_damage_per_second' => 320, 'speed_decrease_pct' => 48, 'attack_rate_decrease_pct' => 70, 'cost' => 135000, 'res_type' => 'dark_elixir', 'time' => 604800,  'lab_req' => 13, 'th_req' => 0],
      10 => ['max_damage_per_second' => 340, 'speed_decrease_pct' => 50, 'attack_rate_decrease_pct' => 72, 'cost' => 175000, 'res_type' => 'dark_elixir', 'time' => 691200,  'lab_req' => 14, 'th_req' => 0],
      11 => ['max_damage_per_second' => 360, 'speed_decrease_pct' => 51, 'attack_rate_decrease_pct' => 73, 'cost' => 230000, 'res_type' => 'dark_elixir', 'time' => 835200,  'lab_req' => 15, 'th_req' => 0],
      12 => ['max_damage_per_second' => 380, 'speed_decrease_pct' => 52, 'attack_rate_decrease_pct' => 74, 'cost' => 350000, 'res_type' => 'dark_elixir', 'time' => 1252800, 'lab_req' => 16, 'th_req' => 0],
    ],
  ],

  'earthquake_spell' => [
    'name' => 'Землетрясение',
    'type' => TYPE_DARK_SPELL,
    'desc' => 'Наносит процентный урон зданиям и стенам в области; на высоких уровнях также повреждает наземные войска.',
    'effect' => 'Процентный урон по зданиям/стенам в области.',
    'targets' => 'buildings',
    'usage' => 'Открытие стен, ослабление центра/ключевых зданий.',
    'unlock_th' => 8,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 125,
    'brew_res_type' => 'dark_elixir',
    'housing_space' => 1,
    'levels' => [
      1 => ['building_damage_pct' => 14.5, 'troop_damage_pct' => 0,  'radius' => 3.5, 'cost' => 0,      'res_type' => 'dark_elixir', 'time' => 0,       'lab_req' => 0,  'th_req' => 0],
      2 => ['building_damage_pct' => 17,   'troop_damage_pct' => 0,  'radius' => 3.8, 'cost' => 6000,   'res_type' => 'dark_elixir', 'time' => 43200,   'lab_req' => 6,  'th_req' => 0],
      3 => ['building_damage_pct' => 21,   'troop_damage_pct' => 0,  'radius' => 4.1, 'cost' => 12000,  'res_type' => 'dark_elixir', 'time' => 86400,   'lab_req' => 7,  'th_req' => 0],
      4 => ['building_damage_pct' => 25,   'troop_damage_pct' => 0,  'radius' => 4.4, 'cost' => 25500,  'res_type' => 'dark_elixir', 'time' => 259200,  'lab_req' => 8,  'th_req' => 0],
      5 => ['building_damage_pct' => 29,   'troop_damage_pct' => 0,  'radius' => 4.7, 'cost' => 42000,  'res_type' => 'dark_elixir', 'time' => 302400,  'lab_req' => 9,  'th_req' => 0],
      6 => ['building_damage_pct' => 29,   'troop_damage_pct' => 5,  'radius' => 4.7, 'cost' => 120000, 'res_type' => 'dark_elixir', 'time' => 691200,  'lab_req' => 12, 'th_req' => 0],
      // На вики лаборатория помечена как "?"; используем ожидаемый порядок (между 12 и 16).
      7 => ['building_damage_pct' => 29,   'troop_damage_pct' => 10, 'radius' => 4.7, 'cost' => 200000, 'res_type' => 'dark_elixir', 'time' => 777600,  'lab_req' => 15, 'th_req' => 0],
      8 => ['building_damage_pct' => 29,   'troop_damage_pct' => 14, 'radius' => 4.7, 'cost' => 330000, 'res_type' => 'dark_elixir', 'time' => 1166400, 'lab_req' => 16, 'th_req' => 0],
    ],
  ],

  'haste_spell' => [
    'name' => 'Ускорение',
    'type' => TYPE_DARK_SPELL,
    'desc' => 'Резко увеличивает скорость союзных войск в области действия.',
    'effect' => 'Резко увеличивает скорость союзных войск.',
    'targets' => 'any',
    'usage' => 'Поддержка хогов/шахтёров/бомберов, быстрый проход.',
    'unlock_th' => 9,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 80,
    'brew_res_type' => 'dark_elixir',
    'housing_space' => 1,
    'levels' => [
      1 => ['speed_increase' => 28, 'duration' => 10, 'radius' => 4.0, 'cost' => 0,      'res_type' => 'dark_elixir', 'time' => 0,       'lab_req' => 0,  'th_req' => 0],
      2 => ['speed_increase' => 34, 'duration' => 15, 'radius' => 4.0, 'cost' => 8000,   'res_type' => 'dark_elixir', 'time' => 86400,   'lab_req' => 7,  'th_req' => 0],
      3 => ['speed_increase' => 40, 'duration' => 20, 'radius' => 4.0, 'cost' => 17000,  'res_type' => 'dark_elixir', 'time' => 172800,  'lab_req' => 8,  'th_req' => 0],
      4 => ['speed_increase' => 46, 'duration' => 25, 'radius' => 4.0, 'cost' => 30000,  'res_type' => 'dark_elixir', 'time' => 259200,  'lab_req' => 8,  'th_req' => 0],
      5 => ['speed_increase' => 52, 'duration' => 30, 'radius' => 4.0, 'cost' => 38500,  'res_type' => 'dark_elixir', 'time' => 345600,  'lab_req' => 9,  'th_req' => 0],
      6 => ['speed_increase' => 56, 'duration' => 30, 'radius' => 4.0, 'cost' => 200000, 'res_type' => 'dark_elixir', 'time' => 777600,  'lab_req' => 15, 'th_req' => 0],
      7 => ['speed_increase' => 56, 'duration' => 30, 'radius' => 5.0, 'cost' => 320000, 'res_type' => 'dark_elixir', 'time' => 1080000, 'lab_req' => 16, 'th_req' => 0],
    ],
  ],

  'skeleton_spell' => [
    'name' => 'Скелеты',
    'type' => TYPE_DARK_SPELL,
    'desc' => 'Призывает скелетов, которые отвлекают оборону и атакуют наземные цели.',
    'effect' => 'Призывает скелетов в области.',
    'targets' => 'ground',
    'usage' => 'Отвлечение Инферно/монолитов, поддержка пушей.',
    'unlock_th' => 11,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 75,
    'brew_res_type' => 'dark_elixir',
    'housing_space' => 1,
    'radius' => 3.5,
    'levels' => [
      1 => ['skeletons_generated' => 12, 'cost' => 0,       'res_type' => 'dark_elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['skeletons_generated' => 13, 'cost' => 11000,   'res_type' => 'dark_elixir', 'time' => 86400,  'lab_req' => 8,  'th_req' => 0],
      3 => ['skeletons_generated' => 14, 'cost' => 17000,   'res_type' => 'dark_elixir', 'time' => 129600, 'lab_req' => 8,  'th_req' => 0],
      4 => ['skeletons_generated' => 15, 'cost' => 25000,   'res_type' => 'dark_elixir', 'time' => 172800, 'lab_req' => 9,  'th_req' => 0],
      5 => ['skeletons_generated' => 16, 'cost' => 40000,   'res_type' => 'dark_elixir', 'time' => 216000, 'lab_req' => 10, 'th_req' => 0],
      6 => ['skeletons_generated' => 17, 'cost' => 50000,   'res_type' => 'dark_elixir', 'time' => 259200, 'lab_req' => 10, 'th_req' => 0],
      7 => ['skeletons_generated' => 18, 'cost' => 75000,   'res_type' => 'dark_elixir', 'time' => 367200, 'lab_req' => 11, 'th_req' => 0],
      8 => ['skeletons_generated' => 19, 'cost' => 135000,  'res_type' => 'dark_elixir', 'time' => 561600, 'lab_req' => 13, 'th_req' => 0],
    ],
  ],

  'bat_spell' => [
    'name' => 'Летучие мыши',
    'type' => TYPE_DARK_SPELL,
    'desc' => 'Призывает летучих мышей, которые атакуют оборону.',
    'effect' => 'Призывает летучих мышей (атакуют здания).',
    'targets' => 'buildings',
    'usage' => 'Снос обороны под фризами/танком.',
    'unlock_th' => 10,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 125,
    'brew_res_type' => 'dark_elixir',
    'housing_space' => 1,
    'radius' => 3.5,
    'levels' => [
      1 => ['bats_generated' => 7,  'cost' => 0,      'res_type' => 'dark_elixir', 'time' => 0,       'lab_req' => 0,  'th_req' => 0],
      2 => ['bats_generated' => 9,  'cost' => 13000,  'res_type' => 'dark_elixir', 'time' => 86400,   'lab_req' => 8,  'th_req' => 0],
      3 => ['bats_generated' => 11, 'cost' => 25500,  'res_type' => 'dark_elixir', 'time' => 172800,  'lab_req' => 8,  'th_req' => 0],
      4 => ['bats_generated' => 16, 'cost' => 35000,  'res_type' => 'dark_elixir', 'time' => 194400,  'lab_req' => 9,  'th_req' => 0],
      5 => ['bats_generated' => 21, 'cost' => 47500,  'res_type' => 'dark_elixir', 'time' => 345600,  'lab_req' => 10, 'th_req' => 0],
      6 => ['bats_generated' => 22, 'cost' => 140000, 'res_type' => 'dark_elixir', 'time' => 604800,  'lab_req' => 13, 'th_req' => 0],
      7 => ['bats_generated' => 23, 'cost' => 220000, 'res_type' => 'dark_elixir', 'time' => 734400,  'lab_req' => 15, 'th_req' => 0],
      8 => ['bats_generated' => 25, 'cost' => 300000, 'res_type' => 'dark_elixir', 'time' => 1123200, 'lab_req' => 16, 'th_req' => 0],
    ],
  ],

  'overgrowth_spell' => [
    'name' => 'Разрастание',
    'type' => TYPE_DARK_SPELL,
    'desc' => 'Покрывает область корнями: здания и войска внутри временно отключаются.',
    'effect' => 'Отключает здания/войска в области на время.',
    'targets' => 'any',
    'usage' => 'Изоляция части базы, отключение опасной обороны.',
    'unlock_th' => 15,
    'brew_time' => 360,
    'training_time' => 0,
    'brew_cost' => 260,
    'brew_res_type' => 'dark_elixir',
    'housing_space' => 2,
    'radius' => 6.0,
    'levels' => [
      1 => ['duration' => 22, 'cost' => 0,      'res_type' => 'dark_elixir', 'time' => 0,      'lab_req' => 0,  'th_req' => 0],
      2 => ['duration' => 23, 'cost' => 62500,  'res_type' => 'dark_elixir', 'time' => 475200, 'lab_req' => 10, 'th_req' => 0],
      3 => ['duration' => 24, 'cost' => 125000, 'res_type' => 'dark_elixir', 'time' => 734400, 'lab_req' => 12, 'th_req' => 0],
      4 => ['duration' => 25, 'cost' => 175000, 'res_type' => 'dark_elixir', 'time' => 864000, 'lab_req' => 14, 'th_req' => 0],
    ],
  ],

  // NOTE: "Ледяная глыба" отсутствует в Home Village оригинального Clash of Clans.


  // Новые/актуальные заклинания (по вики/официальным данным)
  'revive_spell' => [
    'name' => 'Оживление',
    'type' => TYPE_SPELL,
    'desc' => 'Возвращает павшего героя к жизни в области действия.',
    'effect' => 'Воскрешает героя и восстанавливает часть его здоровья.',
    'targets' => 'heroes',
    'usage' => 'Возврат Короля/Королевы/Стража/Чемпионки в решающий момент.',
    'unlock_th' => 15,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 33000,
    'brew_res_type' => 'elixir',
    'housing_space' => 2,
    'radius' => 8,
    'levels' => [
      1 => ['hero_heal_pct' => 55, 'trigger_radius' => 8, 'cost' => 0,        'res_type' => 'elixir', 'time' => 0,        'lab_req' => 0,  'th_req' => 0],
      2 => ['hero_heal_pct' => 60, 'trigger_radius' => 8, 'cost' => 9000000,  'res_type' => 'elixir', 'time' => 691200,   'lab_req' => 15, 'th_req' => 0],
      3 => ['hero_heal_pct' => 65, 'trigger_radius' => 8, 'cost' => 13500000, 'res_type' => 'elixir', 'time' => 777600,   'lab_req' => 16, 'th_req' => 0],
      4 => ['hero_heal_pct' => 70, 'trigger_radius' => 8, 'cost' => 18000000, 'res_type' => 'elixir', 'time' => 864000,   'lab_req' => 16, 'th_req' => 0],
    ],
  ],

  'ice_block_spell' => [
    'name' => 'Ледяной блок',
    'type' => TYPE_DARK_SPELL,
    'desc' => 'Заключает войска в ледяной блок в области: они не атакуют, но получают значительно меньше урона.',
    'effect' => 'Сильно снижает входящий урон по войскам в области на время действия.',
    'targets' => 'any',
    'usage' => 'Сейв героев/танка под мощной обороной, пережить пик урона.',
    'unlock_th' => 14,
    'brew_time' => 180,
    'training_time' => 0,
    'brew_cost' => 150,
    'brew_res_type' => 'dark_elixir',
    'housing_space' => 1,
    'levels' => [
      1 => ['duration' => 6,  'radius' => 4.5, 'incoming_damage_reduction' => 94,  'cost' => 0,      'res_type' => 'dark_elixir', 'time' => 0,       'lab_req' => 0,  'th_req' => 0],
      2 => ['duration' => 6,  'radius' => 4.5, 'incoming_damage_reduction' => 94,  'cost' => 140000, 'res_type' => 'dark_elixir', 'time' => 864000,  'lab_req' => 15, 'th_req' => 0],
      3 => ['duration' => 7,  'radius' => 4.5, 'incoming_damage_reduction' => 94,  'cost' => 180000, 'res_type' => 'dark_elixir', 'time' => 950400,  'lab_req' => 16, 'th_req' => 0],
      4 => ['duration' => 8,  'radius' => 4.5, 'incoming_damage_reduction' => 94,  'cost' => 220000, 'res_type' => 'dark_elixir', 'time' => 1036800, 'lab_req' => 16, 'th_req' => 0],
      5 => ['duration' => 9,  'radius' => 4.5, 'incoming_damage_reduction' => 94,  'cost' => 260000, 'res_type' => 'dark_elixir', 'time' => 1123200, 'lab_req' => 17, 'th_req' => 0],
    ],
  ],

];
